CreateThread(function()
	blipBoat = AddBlipForCoord(Config.BoatSpawn)
	SetBlipSprite(blipBoat, 410)
	SetBlipDisplay(blipBoat, 4)
	SetBlipScale(blipBoat, 0.7)
	SetBlipColour(blipBoat, 74)
    SetBlipAsShortRange(blipBoat, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Наеми лодка")
    EndTextCommandSetBlipName(blipBoat)


	blipTrader = AddBlipForCoord(Config.Trader)
	SetBlipSprite(blipTrader, 68)
	SetBlipDisplay(blipTrader, 4)
	SetBlipScale(blipTrader, 0.7)
	SetBlipColour(blipTrader, 74)
    SetBlipAsShortRange(blipTrader, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Търговец")
    EndTextCommandSetBlipName(blipTrader)
end)